#ifndef BLE_ATT_H
#define BLE_ATT_H

// Attribute Protocol (ATT) wire definitions shared by GATT clients/servers.
// ATT procedures operate on attributes; GATT defines the service model and
// higher-level procedures built on those ATT PDUs.
// TODO for complete LE ATT support:
// - [x] Define LE ATT opcodes, error codes, and little-endian handle helpers.
// - [x] Map every implemented request opcode to its required response opcode.
// - [x] Keep ATT wire definitions independent of GATT services and L2CAP.
// - [x] Test shared wire helpers and request/response mapping directly.
// - [ ] Verify ATT client/server procedures over a BLE controller and radio.
// Scope: LE ATT. BR/EDR ATT bearers and optional EATT bearer integration are
// handled outside this shared LE wire-definition header.
#include <stdint.h>

#ifndef BLE_ATT_VALUE_MAX
#ifdef BLE_GATT_ATT_VALUE_MAX
#define BLE_ATT_VALUE_MAX BLE_GATT_ATT_VALUE_MAX
#else
#define BLE_ATT_VALUE_MAX 512u
#endif
#endif

enum {
    BLE_ATT_OP_ERROR_RSP = 0x01,
    BLE_ATT_OP_EXCHANGE_MTU_REQ = 0x02,
    BLE_ATT_OP_EXCHANGE_MTU_RSP = 0x03,
    BLE_ATT_OP_FIND_INFO_REQ = 0x04,
    BLE_ATT_OP_FIND_INFO_RSP = 0x05,
    BLE_ATT_OP_FIND_BY_TYPE_VALUE_REQ = 0x06,
    BLE_ATT_OP_FIND_BY_TYPE_VALUE_RSP = 0x07,
    BLE_ATT_OP_READ_BY_TYPE_REQ = 0x08,
    BLE_ATT_OP_READ_BY_TYPE_RSP = 0x09,
    BLE_ATT_OP_READ_REQ = 0x0a,
    BLE_ATT_OP_READ_RSP = 0x0b,
    BLE_ATT_OP_READ_BLOB_REQ = 0x0c,
    BLE_ATT_OP_READ_BLOB_RSP = 0x0d,
    BLE_ATT_OP_READ_BY_GROUP_TYPE_REQ = 0x10,
    BLE_ATT_OP_READ_BY_GROUP_TYPE_RSP = 0x11,
    BLE_ATT_OP_WRITE_REQ = 0x12,
    BLE_ATT_OP_WRITE_RSP = 0x13,
    BLE_ATT_OP_PREPARE_WRITE_REQ = 0x16,
    BLE_ATT_OP_PREPARE_WRITE_RSP = 0x17,
    BLE_ATT_OP_EXECUTE_WRITE_REQ = 0x18,
    BLE_ATT_OP_EXECUTE_WRITE_RSP = 0x19,
    BLE_ATT_OP_HANDLE_VALUE_NOTIFICATION = 0x1b,
    BLE_ATT_OP_HANDLE_VALUE_INDICATION = 0x1d,
    BLE_ATT_OP_WRITE_COMMAND = 0x52,
    BLE_ATT_OP_SIGNED_WRITE_COMMAND = 0xd2,
    BLE_ATT_OP_MULTIPLE_HANDLE_VALUE_NOTIFICATION = 0x23,
    BLE_ATT_OP_READ_MULTIPLE_REQ = 0x0e,
    BLE_ATT_OP_READ_MULTIPLE_RSP = 0x0f,
    BLE_ATT_OP_READ_MULTIPLE_VARIABLE_REQ = 0x20,
    BLE_ATT_OP_READ_MULTIPLE_VARIABLE_RSP = 0x21
};

static inline uint16_t ble_att_get_u16(const uint8_t *p) {
    return (uint16_t)p[0] | (uint16_t)p[1] << 8;
}

static inline void ble_att_put_u16(uint8_t *p, uint16_t value) {
    p[0] = (uint8_t)value;
    p[1] = (uint8_t)(value >> 8);
}

enum {
    BLE_ATT_ERR_INVALID_HANDLE = 0x01,
    BLE_ATT_ERR_READ_NOT_PERMITTED = 0x02,
    BLE_ATT_ERR_WRITE_NOT_PERMITTED = 0x03,
    BLE_ATT_ERR_INVALID_PDU = 0x04,
    BLE_ATT_ERR_INSUFFICIENT_AUTHENTICATION = 0x05,
    BLE_ATT_ERR_REQUEST_NOT_SUPPORTED = 0x06,
    BLE_ATT_ERR_INVALID_OFFSET = 0x07,
    BLE_ATT_ERR_INSUFFICIENT_AUTHORIZATION = 0x08,
    BLE_ATT_ERR_ATTRIBUTE_NOT_FOUND = 0x0a,
    BLE_ATT_ERR_ENCRYPTION_KEY_SIZE_TOO_SHORT = 0x0c,
    BLE_ATT_ERR_INVALID_ATTRIBUTE_LENGTH = 0x0d,
    BLE_ATT_ERR_UNLIKELY_ERROR = 0x0e,
    BLE_ATT_ERR_INSUFFICIENT_ENCRYPTION = 0x0f,
    BLE_ATT_ERR_UNSUPPORTED_GROUP_TYPE = 0x10,
    BLE_ATT_ERR_INSUFFICIENT_RESOURCES = 0x11,
    BLE_ATT_ERR_VALUE_NOT_ALLOWED = 0x13
};

// Compatibility aliases for existing GATT server/application error handling.
#ifndef BLE_GATT_ATT_VALUE_MAX
#define BLE_GATT_ATT_VALUE_MAX BLE_ATT_VALUE_MAX
#endif
#define BLE_GATT_ATT_ERR_INVALID_HANDLE BLE_ATT_ERR_INVALID_HANDLE
#define BLE_GATT_ATT_ERR_READ_NOT_PERMITTED BLE_ATT_ERR_READ_NOT_PERMITTED
#define BLE_GATT_ATT_ERR_WRITE_NOT_PERMITTED BLE_ATT_ERR_WRITE_NOT_PERMITTED
#define BLE_GATT_ATT_ERR_INVALID_PDU BLE_ATT_ERR_INVALID_PDU
#define BLE_GATT_ATT_ERR_REQUEST_NOT_SUPPORTED BLE_ATT_ERR_REQUEST_NOT_SUPPORTED
#define BLE_GATT_ATT_ERR_INVALID_OFFSET BLE_ATT_ERR_INVALID_OFFSET
#define BLE_GATT_ATT_ERR_ATTRIBUTE_NOT_FOUND BLE_ATT_ERR_ATTRIBUTE_NOT_FOUND
#define BLE_GATT_ATT_ERR_INVALID_ATTRIBUTE_LENGTH BLE_ATT_ERR_INVALID_ATTRIBUTE_LENGTH
#define BLE_GATT_ATT_ERR_INSUFFICIENT_RESOURCES BLE_ATT_ERR_INSUFFICIENT_RESOURCES
#define BLE_GATT_ATT_ERR_UNLIKELY_ERROR BLE_ATT_ERR_UNLIKELY_ERROR
#define BLE_GATT_ATT_ERR_INSUFFICIENT_ENCRYPTION BLE_ATT_ERR_INSUFFICIENT_ENCRYPTION
#define BLE_GATT_ATT_ERR_INSUFFICIENT_AUTHORIZATION BLE_ATT_ERR_INSUFFICIENT_AUTHORIZATION
#define BLE_GATT_ATT_ERR_INSUFFICIENT_AUTHENTICATION BLE_ATT_ERR_INSUFFICIENT_AUTHENTICATION
#define BLE_GATT_ATT_ERR_UNSUPPORTED_GROUP_TYPE BLE_ATT_ERR_UNSUPPORTED_GROUP_TYPE
#define BLE_GATT_ATT_ERR_ENCRYPTION_KEY_SIZE_TOO_SHORT BLE_ATT_ERR_ENCRYPTION_KEY_SIZE_TOO_SHORT
#define BLE_GATT_ATT_ERR_VALUE_NOT_ALLOWED BLE_ATT_ERR_VALUE_NOT_ALLOWED

// Return the response opcode for a request, or zero for non-request opcodes.
static inline uint8_t ble_att_response_opcode(uint8_t request_opcode) {
    switch (request_opcode) {
    case BLE_ATT_OP_EXCHANGE_MTU_REQ: return BLE_ATT_OP_EXCHANGE_MTU_RSP;
    case BLE_ATT_OP_FIND_INFO_REQ: return BLE_ATT_OP_FIND_INFO_RSP;
    case BLE_ATT_OP_FIND_BY_TYPE_VALUE_REQ:
        return BLE_ATT_OP_FIND_BY_TYPE_VALUE_RSP;
    case BLE_ATT_OP_READ_BY_TYPE_REQ: return BLE_ATT_OP_READ_BY_TYPE_RSP;
    case BLE_ATT_OP_READ_REQ: return BLE_ATT_OP_READ_RSP;
    case BLE_ATT_OP_READ_BLOB_REQ: return BLE_ATT_OP_READ_BLOB_RSP;
    case BLE_ATT_OP_READ_MULTIPLE_REQ: return BLE_ATT_OP_READ_MULTIPLE_RSP;
    case BLE_ATT_OP_READ_BY_GROUP_TYPE_REQ:
        return BLE_ATT_OP_READ_BY_GROUP_TYPE_RSP;
    case BLE_ATT_OP_WRITE_REQ: return BLE_ATT_OP_WRITE_RSP;
    case BLE_ATT_OP_PREPARE_WRITE_REQ: return BLE_ATT_OP_PREPARE_WRITE_RSP;
    case BLE_ATT_OP_EXECUTE_WRITE_REQ: return BLE_ATT_OP_EXECUTE_WRITE_RSP;
    case BLE_ATT_OP_READ_MULTIPLE_VARIABLE_REQ:
        return BLE_ATT_OP_READ_MULTIPLE_VARIABLE_RSP;
    default: return 0;
    }
}

#endif
